# pyproject.toml
target-version = "py312"

[tool.black]
target-version = ["py312"]

[tool.isort]
split_on_trailing_comma = true

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741"]
